### ISSUE TITLE
Error: Autoload is not a function

### ISSUE THREAD

**Issue by coryfail** [GiovanniCardamone/express-automatic-routes#100]
- **Node Version:** v16.13.0
- **Operating System:** Windows 10
- **Terminal:** Windows Powershell

I'm receiving the error 

`TypeError: autoload is not a function`

Here is my code:

```
const express = require('express')
const autoload = require('express-automatic-routes')

const app = express()

autoload(app, { dir: './src/routes' })

app.listen(process.env.PORT || 3000)
```

This is in JS

**Comment by GiovanniCardamone** [comment]
i am using esm module system, so, if you ise plain vanilla require, you should require in this way:

```
const autoload = require('express-automatic-routes').default
```

or just call default function

```
autoload.default(app, { dir: './src/routes' })
```

if you are using ES module import

```
import autoload from 'express-automatic-routes'
```

let me know if that solve the issue so i can close this
